project:
  type: website

website:
  title: "CR"
  navbar:
    right: # accepts right/left/center; you can also place items individually on the left, right, and center
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: CV.qmd
        text: CV
        # target: _blank # opens link (or page) in a new tab
      - icon: github # add icons as navbar buttons
        href: https://github.com/reitancorp
#        target: _blank
  page-footer:
    background: light # or `dark`
    left: Copyright 2024, Christian Reitan
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}


format:
  html:
    theme: 
      - cosmo
      - styles.scss # I've also removed the `css: styles.css` option that was included by default, since I'll be writing all my sass and css in this single styles.scss file
    mainfont: Jost
    toc: true

editor: visual

